name: 'Supybot IRC Messages Action'
description: 'Send an IRC message to a Supybot instance'
author: 'Vladimir "allejo" Jimenez'
inputs:
  hostname:
    required: true
    description: 'The hostname and port of the Supybot instance'
  credentials:
    required: true
    description: 'Basic authentication; e.g. `username:password` or `password`'
  channel:
    required: true
    description: 'The IRC channel to send this message to'
  message:
    required: true
    description: 'The message to send'
runs:
  using: 'node12'
  main: 'dist/index.js'
