name: 'Supybot IRC Messages Action'
description: 'Send an IRC message to a Supybot instance'
author: 'Vladimir "allejo" Jimenez'
inputs:
  hostname:
    required: true
    description: 'The hostname and port of the Supybot instance'
  credentials:
    required: true
    description: 'Basic authentication; e.g. `username:password` or `password`'
runs:
  using: 'node12'
  main: 'dist/index.js'
