name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install
      - name: Run all our commands
        run: |
          npm run all
      - name: Sample IRC Notification
        if: always()
        uses: ./
        with:
          hostname: ${{ secrets.SUPYBOT_HOST }}
          credentials: ${{ secrets.SUPYBOT_PASSWORD }}
          channel: '#sujevo-dev'
          status: ${{ job.status }}
          default_message: true
